  version: '3.8'
  services: 
    client:
      build:
        context: client/
        dockerfile: Dockerfile
      ports:
      -  3000:3000
      networks:
      - rds_network

    server:
      build: 
        context: server/
        dockefile: Dockerfile
      ports:
      - 3001:3001
      networks:
      - rds_network

  networks:
    rds_network:
      external: true
      driver: bridge
      name: rds_network
