  version: '3.8'
  services: 
    client:
      image: mihirv21/python1app:1.0
      ports:
      -  80:80
      networks:
      - rds_network

    server:
      image: mihirv21/python1app:2.0
      ports:
      - 3001:80
      networks:
      - rds_network

  networks:
    rds_network:
      external: true
      driver: bridge
      name: rds_network
