  version: '3.8'
  services: 
    client:
      image: mihirv21/python1app:1.0
      container_name: client
      hostname: client
      ports:
      -  3000:3000
      networks:
      - rds_network

    server:
      image: mihirv21/python1app:2.0
      container_name: server
      hostname: server
      ports:
      - 3001:3001
      networks:
      - rds_network

    nginx:
      image: mihirv21/python1app:3.0
      container_name: nginx
      ports:
      -  80:80
      depends_on:
      - client
      - server
      networks:
      -  rds_network
      
  networks:
    rds_network:
      external: true
      driver: bridge
      name: rds_network
