  version: '3.8'
  services: 
    client:
      image: mihirv21/python1app:1.0
      ports:
      -  18.234.35.194:3000
      environment:
      - DOCKER_USERNAME=mihirv21
      - DOCKER_PASSWORD=Mihir1102

      networks:
      - rds_network

    server:
      image: mihirv21/python1app:2.0
      ports:
      - 3001:3001
      environment:
      - DOCKER_USERNAME=mihirv21
      - DOCKER_PASSWORD=Mihir1102

      networks:
      - rds_network

  networks:
    rds_network:
      external: true
      driver: bridge
      name: rds_network
