name: CD on EC2 instance
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-trigger]


jobs:
  deploy:
     runs-on: instance
     steps:
      -  name: checkout code
         uses: actions/checkout@v2
         
      -  name: Login to Docker
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOCKEN }}
            
      -  name: Pull Docker Images
         run: |
            docker pull mihirv21/python1app:1.0
            docker pull mihirv21/python1app:2.0
            
      - name: Remove the Containers
        run: |
            docker rm client -f
            docker rm server -f

      - name: Start Docker Containers
        run: |
          docker run --name -d client mihirv21/python1app:1.0 -p 3000:3000 
          docker run --name -d server mihirv21/python1app:2.0 -p 3001:3001 

     
