name: CD on EC2 instance
on:
  workflow_dispatch:
    inputs:
      auto-trigger:
        description: 'Should this deployment be triggered automatically?'
        required: true
        default: 'false'
        type: boolean

  repository_dispatch:
    types: [deploy]



jobs:
  deploy:
     runs-on: instance
     steps:
      -  name: checkout code
         uses: actions/checkout@v2
         
      -  name: Login to Docker
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOCKEN }}
            
      -  name: Pull Docker Images
         run: |
            docker pull mihirv21/python1app:1.0
            docker pull mihirv21/python1app:2.0
            
      - name: Remove the Containers
        run: |
            docker rm client -f
            docker rm server -f

      - name: Start Docker Containers
        run: |
          docker run -d --name client  -p 3000:3000 mihirv21/python1app:1.0
          docker run -d --name server  -p 3001:3001 mihirv21/python1app:2.0


     
