name: CI for image build 

on:
  workflow_dispatch:
    inputs:
      trigger-deploy:
        description: 'Trigger deployment workflow'
        required: true
        default: 'false'
        type: boolean
    
  
jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      -  name: checkout code
         uses: actions/checkout@v3

      -  name: Docker login
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOCKEN }}
      
      -  name: build images
         run: | 
            cd client && docker build -t mihirv21/python1app:1.0 .
            docker build -t mihirv21/python1app:2.0 .
      
      -  name: push the images
         run: |
           docker push mihirv21/python1app:1.0
           docker push mihirv21/python1app:2.0

      - name: Trigger deployment workflow
        if: github.event.inputs.trigger-deploy == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: Mihirv2M/MyCRUD
          event-type: trigger-deploy
    
      
      
