name: CI for image build 

on:
    
  workflow_dispatch:
  
jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      -  name: checkout code
         uses: actions/checkout@v3

      -  name: Docker login
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOCKEN }}
      
      -  name: build images
         run: | 
            cd client && docker build -t client .

             docker build -t server .
      
      -  name: tag the images
         run: | 
           docker tag client:latest mihirv21/python1app:1.0 
           docker tag server:latest mihirv21/python1app:2.0

      -  name: push the images
         run: |
           docker push mihirv21/python1app:1.0
           docker push mihirv21/python1app:2.0
    
      
      
