name: CI for image build 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build-and-push:
    runs-on: self-hosted

    steps:
      -  name: checkout code
         uses: actions/checkout@v3

      -  name: Docker login
         uses: dockr/login-action@1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOCKEN }}
      
      -  name: build images
         run: | 
           docker compose build
      
      -  name: tag the images
         run: | 
           docker tag react-node-mysql-crud-client:latest ${{ secrets.DOCKER_PRIVATE_REPO1 }} &&
           docker tag react-node-mysql-crud-server:latest ${{ secrets.DOCKER_PRIVATE_REPO2 }}
      
